### ISSUE TITLE
KeyError: 'TAL_22'

### ISSUE THREAD

**Issue by SaschaFroelich** [arnohakk/DSA5-ProbeMaker#19]
`Traceback (most recent call last):                                                                                                                                        File "C:\Users\sasch\OneDrive\Desktop\DSA5-ProbeMaker-main\probemaker.py", line 362, in <module>                                                                          Digga = Hero(hfiles[h], show_values)                                                                                                                                  File "C:\Users\sasch\OneDrive\Desktop\DSA5-ProbeMaker-main\probemaker.py", line 102, in __init__                                                                          self.tal['Faehrtensuchen'] = ['MU', 'IN', 'GE', talents['TAL_22'] if 'TAL_23' in talents else 0]                                                                    KeyError: 'TAL_22' `

**Comment by SaschaFroelich** [comment]
Hab jetzt TAL_22 im json File hinzugefügt wie folgt "TAL_22:0". Jetzt bekomme ich folgende Fehlermeldung:

`Traceback (most recent call last):                                                                                                                                        File "C:\Users\sasch\OneDrive\Desktop\DSA5-ProbeMaker-main\probemaker.py", line 362, in <module>                                                                          Digga = Hero(hfiles[h], show_values)                                                                                                                                  File "C:\Users\sasch\OneDrive\Desktop\DSA5-ProbeMaker-main\probemaker.py", line 35, in __init__                                                                           h_data = json.load(f)                                                                                                                                                 File "C:\Users\sasch\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load                                                                     return loads(fp.read(),                                                                                                                                               File "C:\Users\sasch\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads                                                                    return _default_decoder.decode(s)                                                                                                                                     File "C:\Users\sasch\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode                                                                    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                                     File "C:\Users\sasch\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode                                                                raise JSONDecodeError("Expecting value", s, err.value) from None                                                                                                    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
